### ISSUE TITLE
birdnet_verify not updating with verifications

### ISSUE THREAD

**Issue by aikibraki** [nationalparkservice/NSNSDAcoustics#13] opened 2024-02-16 20:07 UTC
It returns the following after inputting a user verification:

> Updating  with new verifications.
> Error in if (file == "") file <- stdout() else if (is.character(file)) { : 
>   argument is of length zero

seems from line 210 of birdnet_verify that the file name is meant to be inserted here:

> message("Updating ", basename(finame), " with new verifications.")

- so maybe linked with case sensitivity in ".WAV" vs. ".wav"?
- or some issue with the finame object, which appears to be missing somehow?

R and RStudio are running on their latest versions

**Comment by cbalantic** [comment] 2024-02-20 18:52
There are lines of code in birdnet_verify that attempt to reconcile the WAV vs wav case, so I hope this is not the problem, but it's possible this is just a new bug! I don't have enough info to diagnose it from this alone and would have to step through with a debugger to figure it out. 

From here, https://github.com/nationalparkservice/NSNSDAcoustics/blob/main/R/birdnet_verify.R line 210 is about frequency bins, so I can't quite discern the error source. 

A few questions:

Did you run birdnet_format() already? (i.e., do you have csv files with a "verify" column in them?) 

After you get this error, what happens when you run traceback()? 

What happens if you wrap birdnet_verify in a debugonce() statement, and then step through with the debugger and check outputs line by line while in the debug environment? (This is more labor intensive, but short of being able to dig in and debug it myself, it's what I would do to learn more about the error.)

I'm hopeful we can figure out what is going on!

**Comment by aikibraki** [comment] 2024-02-20 21:25
Thanks for the help! 

The data are formatted with birdnet_format() already. It appears that the formatted files _with_ detections use WAV, while the ones without use wav -- not sure if this is important.

In birdnet_verify.R, the line is 393. I had been using view(birdnet_verify) inside RStudio, where it is line 210.

 
Here's the results of the traceback()
```
6: utils::write.table(x = new.results, file = finame, row.names = FALSE, 
       col.names = TRUE, sep = ",", dec = ".", qmethod = "double")
5: eval(expr, p)
4: eval(expr, p)
3: eval.parent(Call)
2: write.csv(x = new.results, file = finame, row.names = FALSE)
1: birdnet_verify(data = to.verify, verification.library = ver.lib, 
       audio.directory = "[audio directory]", 
       results.directory = "[results directory]", 
       overwrite = FALSE, play = TRUE, frq.lim = c(0, 12), buffer = 1, 
       box.col = "blue", spec.col = monitoR::gray.3())
```

Running debugonce(birdnet_verify), watching the environment I found that:
this.wav is "character (empty)" and so is finame, which relies on this.wav
correct.ids is "integer (empty)"
these are empty from the point that they are created all the way through the end of the function.

I hope this is helpful!

**Comment by cbalantic** [comment] 2024-02-20 22:52
It's not clear to me what's going on yet. I'm not able to reproduce this error on my end, and it's hard to diagnose without knowing whether your call to birdnet_verify() is pointing to valid files/folders.

A few more questions: 

(1) When you run the example in the birdnet_verify helpfile, does it run correctly?

(2) Could you run and following and show me an example of some of the outputs?

list.files(
      path = 'path/to/your/results/directory/', 
      full.names = TRUE,
      recursive = TRUE
)

(3) Can you verify that your recordings follow the name convention SITEID_YYYYMMDD_HHMMSS, and/or provide an example of what your recording names look like? 

Thanks!

**Comment by cbalantic** [comment] 2024-02-22 22:53
If you are willing, could you contact me by email (cathleen_balantic [at] nps.gov) and send me a few of your formatted csv files? I don't think I can solve this otherwise! Thank you for considering.

**Comment by aikibraki** [comment] 2024-02-23 15:23
Sent!

**Comment by cbalantic** [comment] 2024-02-23 21:15
As suggested by @aikibraki, this was indeed a case issue with .wav vs .WAV. Fixed with commit https://github.com/nationalparkservice/NSNSDAcoustics/commit/85a2eac21a424c526b99ac5db9e412bc4d02ae41

**Closed by cbalantic** 2024-02-23 21:15 UTC
